### ISSUE TITLE
command :info, objects not found!

### ISSUE THREAD

**Issue by dmerrick** [kostya/eye#100]
First, I want to thank you for your prompt help on #99. We've upgraded to 0.7.pre and as far as I can tell it's no longer timing out.

Unfortunately, we occasionally get the output `command :info, objects not found!` from the info command.

Usually this is in the context of an init script, so the command is `eye info resque_workers`. It would be really nice to track down why this is happening, so we can start to trust reliability of eye info.

**Comment by kostya** [comment]
any progress here?
