### ISSUE TITLE
Restart by dependency instead of alphabetically

### ISSUE THREAD

**Issue by mkamioner** [kostya/eye#105]
First off - Thanks! I love using eye! It makes our lives so much easier.

We have several services running in eye. When we use
````
eye restart all
````
the services are restarted in alphabetical order. But service A, C & G are dependent on Z. So A, C and G will restart, then Z will restart. And when Z restarts, A, C and G restart again!

It would be great if eye was able to identify which services are dependencies are restart them first in order to be more efficient on restarts

Thanks!
Mike

**Comment by kostya** [comment]
dependencies makes things harder. order of restart not easy to implement. depend_on is experimental feature. personally i avoid to use this, and prefer to make dependency on application level, for example client die if can't connect to server. so if you restart server, all clients just die and then ups by eye.

need to think more about dependencies.

**Comment by mkamioner** [comment]
Hmmm, I will see if I can move off of dependencies. Thanks!

**Comment by mkamioner** [comment]
I was thinking - maybe you can add a restart order to each process? So that way when I do a restart I can manually decide the order that processes start - is that hard to implement?

**Comment by kostya** [comment]
What if leaf processes would be ignored when group restarted, when main process restarted, leafs would restarted too. But there is one problem, if leaf process was stopped by hands, it remains unmonitored, even if restart a group.
