### ISSUE TITLE
Hide env from log file

### ISSUE THREAD

**Issue by innovia** [kostya/eye#106]
Hi Konstantin

is there a way to block / override env vars in the log

````txt

08.01.2015 00:56:47 INFO  -- [services:SomeProcess] => restore  (reason: crashed)
08.01.2015 00:56:47 INFO  -- [services:SomeProcess] pid_file not found, starting...
08.01.2015 00:56:47 INFO  -- [services:SomeProcess] switch :starting [:down => :starting] (reason: crashed)
08.01.2015 00:56:47 INFO  -- [services:SomeProcess] daemonizing: `./combinedMetrics.rb --config-file=/home/ec2-user/metrics.yml` with start_grace: 2.5s, env: 'NODE_PATH=/usr/local/lib/node_modules NODE_ENV=production .....
````

**Comment by kostya** [comment]
why? is it too big?

**Comment by innovia** [comment]
security issues, I need the log of eye attached to email, and also transport it to s3 for logstash later on

**Comment by kostya** [comment]
you can have also some passwords in start_command or somewhere also. Eye log needed actually only for eye debug issues. Why you send it to something?

**Comment by innovia** [comment]
i did it at first to see if we get out of memory (per process) issues - i attached it to the email

but i guess i can remove it now since i have already in the subject:

 missedMessages_1 on ios - Bounded memory(<150Mb): [148Mb, 149Mb, *150Mb, *153Mb, *154Mb] send to [:restart]

**Comment by kostya** [comment]
you can use `eye history` and send it as report.
