### ISSUE TITLE
eye status myapp error: "unknown status for :application=myapp"

### ISSUE THREAD

**Issue by bradenwright** [kostya/eye#108]
So I was grepping "eye info myapp" command to try to do what the status command is intended for and you mentioned that there was a status command I can use ( https://github.com/hamann/eye-chef-cookbook/issues/8#issuecomment-73030530 ).  So thanks for the advice as it will simplify things but when I tried to use that command I'm getting an error, it pretty generic:
unknown status for :application=myapp

I tried searching web and your eye git project, but haven't been able to figure it out (all other commands with eye seem to be working: load, start, stop, monitor, etc).  Any advice would be appreciated.  

Everything else has gone really smooth trying out eye.... so kudos and thanks!

**Comment by kostya** [comment]
eye status works only for one process: `eye status process_name`

**Comment by bradenwright** [comment]
my apologize thank you kindly.  I have really enjoyed using Eye
