### ISSUE TITLE
Celluloid upgrade

### ISSUE THREAD

**Issue by lypanov** [kostya/eye#109]
Is there any status on the 0.7.0 branch? We're running eye to monitor sidekiq in production and would very much like to get up to date on the latest sidekiq, alas this also requires the latest revision of celluloid which conflicts with eye.

We've tried looking into other options but frankly the idea of multiple configurations of bundler makes me want to cry (one is already too much).

**Comment by kostya** [comment]
i experiencing eye 10-13% more memory usage with celluloid 0.16, which is makes me want to cry, because eye memory usage was not small before. So i'm not hurry to update. If it really needed, I can push some pre version to rubygems.

**Comment by lypanov** [comment]
Okay we're heavily memory constrained also so we'll skip the sidekiq/eye upgrade pair and wait for a hopeful future memory reducing release of celluloid! :) Thank you for the explanation. Fully understand now.

**Comment by kostya** [comment]
we not using eye in Gemfile, and install it as system tool, it not requires to depend on anything.
