### ISSUE TITLE
Deployment with AWS EC2/ElasticBeanstalk?

### ISSUE THREAD

**Issue by uhrohraggy** [kostya/eye#112]
How would we instantiate this when deploying to AWS via ElasticBeanstalk (in a Rails environment), where multiple virtual servers/AMIs could spin up or down depending on bandwidth, and where does the delayed_job.eye config file go? Below is the post script file I have to use to get delayed_job up and running without eye due to permissions and current user context during post deploy:

*.ebextensions/99delayed_job.config*
```commands:
  create_post_dir:
    command: "mkdir /opt/elasticbeanstalk/hooks/appdeploy/post"
    ignoreErrors: true
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/post/99_restart_delayed_job.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/usr/bin/env bash
      . /opt/elasticbeanstalk/support/envvars
      cd $EB_CONFIG_APP_CURRENT
      su -c "touch log/delayed_job.log && chmod 766 log/delayed_job.log" $EB_CONFIG_APP_USER
      su -c "chmod +x script/delayed_job" $EB_CONFIG_APP_USER
      cd tmp/ember-rails/
      su -c "sudo chmod 766 ember-data.js && sudo chmod 766 ember.js" $EB_CONFIG_APP_USER
      chmod 766 $EB_CONFIG_APP_SUPPORT/pids
      cd $EB_CONFIG_APP_CURRENT      
      su -c "RAILS_ENV=production script/delayed_job --pid-dir=$EB_CONFIG_APP_SUPPORT/pids restart" $EB_CONFIG_APP_USER
```

Do the eye installation statements go in the above file, and then start the config, something like this? 
```
sudo /usr/local/ruby/1.9.3/bin/gem install eye
sudo ln -sf /usr/leye l examples/ocal/ruby/1.9.3/bin/eye /usr/local/bin/eye
#your delayed_job.eye from examples/delayed_job.eye
eye l /var/app/current/bin/delayed_job.eye
```

**Comment by kostya** [comment]
Never worked with AWS EC2/ElasticBeanstalk, so cant help, and dont know what you want...

**Comment by uhrohraggy** [comment]
No worries, appreciate it and thought if you had could save a bunch of time. I'll work on it and add a pull request if I can get it working. Thanks for such a quick reply!

**Comment by dugjason** [comment]
Hey @uhrohraggy, did you ever have any luck with this? I've been fighting various EBS deploy issues, including running into issues getting eye to load it's config on deploy

**Comment by uhrohraggy** [comment]
@dugjason Unfortunately, I never did and gave up on it. The only workaround (wouldn't call it a solution) I can think of is deploying your config file with the project, then remoting into one of the AMIs and starting eye as a daemon. Of course, if that AMI goes down or gets replaced you're SOL and would have to restart it manually, so you could potentially run the daemon in a separate Background Worker, but of course there would be security and networking considerations...the juice was not worth the squeeze for me.

**Comment by dugjason** [comment]
@uhrohraggy no worries - thanks for getting back to me. I've been SSHing into the machines to start Eye manually, but as you said; each time the machine is replaced, I need to do it again.
I'll try to remember to update this thread if I do get to the bottom of it

**Comment by fields** [comment]
I don't know if this exactly what you're looking for, but I set up an rvm wrapper for eye, and then I put this in the crontab for my limited user account:

    @reboot  /usr/local/rvm/bin/bootup_eye load /path/to/rails/production/shared/system/config.eye

for the services I want to monitor. The config file is deployed as with everything else, and the AMI is snapshotted with the crontab for that user so it starts on every boot.

**Comment by nathwill** [comment]
we set up start-on-boot via a systemd unit for our OpenStack VMs, which works pretty well.

```ini
[Unit]
Description=Misc App

[Install]
WantedBy=multi-user.target

[Service]
WorkingDirectory=/srv/my-app/current
User=deploy
Group=deploy
EnvironmentFile=/srv/my-app/.rbenv-vars
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/rbenv/shims/bundle exec eye load /srv/my-app/current/config/myapp.eye
```

**Comment by dugjason** [comment]
I came back to this today, and I think I've managed to work out a decent solution;

I store what I want in my Crontab in .ebextensions/cron/crontab:

```
# .ebextensions/cron/crontab
* 0 * * * root /opt/rubies/ruby-2.2.2/bin/eye load /var/app/current/config/eye/*.eye
```

Then in an .ebextensions config file:

```
container_commands:
  01_remove_old_cron_jobs:
    command: "crontab -r || exit 0"
  02_cronjobs:
    command: "echo '' > crontab; cat .ebextensions/cron/crontab >> crontab"
    leader_only: true
```

I clear out the old crontab, and refresh it with whatever is in my crontab file (above). I'm not 100% sure which user the crontab belongs to, but it seems to work
