### ISSUE TITLE
Signal to tell eye daemon to reopen eye log file?

### ISSUE THREAD

**Issue by sentience** [kostya/eye#113]
I’m using logrotate to rotate the eye daemon’s log file. When rotation occurs, I need to tell the eye daemon to reopen its log file to begin logging to the new file.

Does the eye daemon support a signal (e.g. USR1 like nginx, Unicorn and others) that will tell it to reload gracefully, or is there some other way to do this?

**Comment by smt116** [comment]
You can use `copytruncate` option in logrotate. Just keep in mind that logrotate will copy the log file and then truncate the original file (so it may **not** work if the log file size takes more than 50% of available disk space)

**Comment by sentience** [comment]
Using `copytruncate` is not an option for me, because I’m using rsyslog to transmit the log to a log aggregation server. For rsyslog to pick up the new log file correctly, the file must have a new inode on disk, which you don’t get when you truncate the existing log file.

**Comment by kostya** [comment]
there is also usr1: https://github.com/kostya/eye/blob/master/bin/loader_eye#L64
or use can rotate it by eye:
```ruby
Eye.config do
  logger "/tmp/eye.log", 7, 10.megabytes
end
```

**Comment by sentience** [comment]
Thanks, @kostya!

**Comment by kostya** [comment]
eye also support logger to syslog: 
https://github.com/kostya/eye/issues/81

**Comment by ktimothy** [comment]
@kostya so does eye reopen only its own log? Or does it reopen logs files, set by `stdall` options?

**Comment by kostya** [comment]
Only own logger. It not reopen stdall files, and not sure this is possible. You also can just restart process to reopen stdall.

**Comment by ktimothy** [comment]
Ok, I have an idea: when spawning child process, create a `IO.pipe` and send its `write_io` to child process as `:stdout` (same goes with `:stderr`). Then eye just reads `read_io` of that pipe and redirects to appropriate log file (set by `stdall`). What do you think, @kostya?

**Comment by kostya** [comment]
i not actually know, how it would work when there is gigabytes of logs of 100 processes, whould consume cpu or not?

right now there is a way to send command to reopen logs, if process self-daemonized and write logs by itself, and support signal to reopen, like this: https://github.com/kostya/eye/issues/104
