### ISSUE TITLE
checks by thread

### ISSUE THREAD

**Issue by grimm26** [kostya/eye#114]
When monitoring something like puma which may be threaded, can CPU and memory checks be set with thresholds per thread?

**Comment by kostya** [comment]
what the use case?
in linux i tried and for every pid for all threads(lwp) get the same rss, and cpu as for main process.
at least from sigar gem.

**Comment by kostya** [comment]
irb
```
require 'eye'
Eye::Control
pid = 21618 # sidekiq pid
pids = `ps -eLf | grep #{pid} | awk '{print $4}'`.split; pids << pid; pids.uniq!
pids.map { |p| Eye::SystemResources.memory(p) }
pids.map { |p| Eye::SystemResources.cpu(p) }
```

**Comment by grimm26** [comment]
The use case is if I set the threshold for puma cpu at 90 and I have 4 cpus and 4 puma threads.  If each thread is using 30% cpu, then puma would show 120% usage and exceed the threshold, right?  But this situation is fine since we're not really taxing the system.

**Comment by kostya** [comment]
you can set cpu limit as 4 * 90, it should work

**Comment by grimm26** [comment]
Yes, but that does not have the granularity to catch a single thread pegging a cpu.  There must be a way to do this :-)

**Comment by kostya** [comment]
sigar gem not support to get lwp list, but you can use it in not portable way, like this, write custom checker:

```ruby
class ThreadsCpu < Eye::Checker::Measure
  def get_value
    pids = defer { `ps -eLf | grep #{@pid} | awk '{print $4}'`.split.map(&:to_i) }
    pids -= [@pid]
    info pids.inspect

    sum_cpu = pids.inject(0) do |sum, pid|
      info pid
      sum + Eye::SystemResources.cpu(pid).to_i
    end
    sum_cpu
  end
end

Eye::Checker.register(ThreadsCpu)

Eye.app :bla do
  process :a do
    pid_file "/tmp/a.pid"
    start_command "ruby -e '10.times { Thread.new { loop { sleep 0.001 } } } ; sleep'"
    daemonize true

    check :threads_cpu, :every => 10.seconds, :below => 200, :times => 50
  end
end

```
