### ISSUE TITLE
strange eye xinfo -c output

### ISSUE THREAD

**Issue by grimm26** [kostya/eye#116]
Some of the output for checks in `eye xinfo -c` looks weird.  Check out the second :times: line below.  Is that normal?
```:checks:
              :cpu:
                :every: 30
                :below: 90
                :times: 3
                :type: :cpu
              :memory:
                :every: 30
                :below: 1048576000
                :times: &1
                - 3
                - 5
                :type: :memory
```

**Comment by grimm26** [comment]
I should also mention that I have the data for checks and other info in a data structure that I then use to construct the eye config.  Example: ``` 
PUMA['checks'].each do |type, settings|    
  check type.to_sym, every: settings['every'], below: settings['threshold'], times: settings['times']
end```

And PUMA['checks']['memory']['times'] = [3,5]

**Comment by kostya** [comment]
this how yaml works:
```
y = [3,5]; x = {:a => y, :b => y}; puts YAML.dump(x)
---
:a: &1
- 3
- 5
:b: *1
```
