### ISSUE TITLE
Possible to use Eye without config file, direct Ruby interface?

### ISSUE THREAD

**Issue by olavolav** [kostya/eye#117]
I'm writing a worker process supervisor with a dynamic number of workers, and are considering using Eye for the actual starting/stopping/monitoring. I.e. my supervisor would handle the logic about how many processes of which kind are needed at any given time, and send that information to Eye for the actual execution.

Is there a nicer, more direct way that creating an automatic Eye config file and triggering a system call to load the new config into Eye?

**Comment by kostya** [comment]
i think should be easy to write:

you can do it in `bundle console`:
```ruby
Eye::Control.command('load', File.expand_path('examples/test.eye'))
Eye::Control.command('info_data')
Eye::Control.command('stop', 'all')
```

to work in more low level, read how load command work: https://github.com/kostya/eye/blob/master/lib/eye/controller/load.rb#L11

or for example https://github.com/tablexi/eye-patch, which write self yml configs.

**Comment by olavolav** [comment]
Great, I'll take a look, thanks!

**Comment by kostya** [comment]
you can ask questions here, if it appears
