### ISSUE TITLE
Standalone usage of Eye

### ISSUE THREAD

**Issue by nicoh** [kostya/eye#119]
Hello, it's more a question than an issue. I would like to use Eye within my own Ruby application. That means depending on some programm states I would like to start/stop and monitor processes with Eye. I wonder whether there is an example which shows how I can use Eye without the Command Line Interface. Basically, an example which shows how to initialize the Eye environment, start a process etc. with the bare Eye API. Any help in this direction is appreciated. Thanks.

**Comment by kostya** [comment]
here i write about similar https://github.com/kostya/eye/issues/117

**Comment by nicoh** [comment]
Thanks! I will check this out.
