### ISSUE TITLE
eye w does not reset tty when exit

### ISSUE THREAD

**Issue by poopops** [kostya/eye#120]
Hi Konstantin

Im running eye 0.6.4 (via the gem install) im seeing an issue when I type eye w and then use CTRL-C eye does not reset the tty and as result text is not showing as it prints

when I type reset, the text comes back

**Comment by kostya** [comment]
eye using just `watch` command: https://github.com/kostya/eye/blob/master/lib/eye/cli.rb#L158
suggest something?

**Comment by poopops** [comment]
probably something is messed up on my end
