### ISSUE TITLE
What does triggers: flapping do?

### ISSUE THREAD

**Issue by shlima** [kostya/eye#121]
Hello, could you please describe this config option

**Comment by kostya** [comment]
Flapping trigger needed when sometimes process can't start, and crashed every time, to switch it to unmonitored state.

```
trigger :flapping, :times => 10, :within => 1.minute, :retry_in => 10.minutes, :retry_times => 15
```
if process crashed 10 times within 1.minute, trigger put it to unmonitored state, and then retry to start it again in 10.minutes (for 15 periods). To save cpu or for other reasons.

here is params for flapping: https://github.com/kostya/eye/blob/master/lib/eye/trigger/flapping.rb#L6
