### ISSUE TITLE
Is there documentation for the various checks?

### ISSUE THREAD

**Issue by gerrywastaken** [kostya/eye#126]
For instance I'm trying to figure out how the file_touched check works. Does it just check if the file has been touched since last time. I see a delete param, however I can't work out what the default is or what it truly means. I've looked at the spec but that doesn't really help. Am I missing docs somewhere or do they still need to be written?

I love eye, btw. It's fantastic, great work. :)

**Comment by kostya** [comment]
`check :file_touched, :every => 10.seconds, :file => "/tmp/bla", :delete => true`

eye check file /tmp/bla everu 10.seconds, if it appears, eye restart the process, and delete file.

there is no other docs, than code and specs.
