### ISSUE TITLE
reload_command request

### ISSUE THREAD

**Issue by hryamzik** [kostya/eye#127]
It would be very nice to have a reload command. In fact it might not be the only missing command so automatic mapping of unknown commands could really cover a lot of cases. For example ``` eye configtest myapp ``` could try to execute the ```configtest_command``` and fail only if it's not presented.

**Comment by kostya** [comment]
there is already user_command: https://github.com/kostya/eye/commit/c0dbfcb1f9efc731d2d81b139700ae863eb0375d
https://github.com/kostya/eye/issues/65

**Comment by hryamzik** [comment]
Wow, that's great! What's the proper way to define it?

```
    user_commands = {
        'test': 'echo test| logger -t eye',
    }
```

Doesn't seem to be valid.

**Comment by kostya** [comment]
```ruby
     Eye.application("app") do
        process("bla") do
          pid_file "/tmp/1.pid"
          start_command "sleep 10"
          daemonize!
          command :abcd, "touch /tmp/2"
        end
      end
```

`eye us(er_command) abcd bla`

**Comment by hryamzik** [comment]
Great, thanks!
