### ISSUE TITLE
load_env stops working 

### ISSUE THREAD

**Issue by shlima** [kostya/eye#128]
Hello, I have the following config:

``` ruby
$ROOT = File.expand_path(File.join(File.dirname(__FILE__), '../'))

Eye.app 'chat' do
  load_env File.join($ROOT, '/.env')
  working_dir $ROOT

  group 'web' do
    ENV.fetch('THIN_WEB_SERVERS')
  end
end

```

After upgrading to ruby 2.2.2 eye stops loading my .env file (I catch the key not found: "THIN_WEB_SERVERS" error)

**Comment by shlima** [comment]
I see the refactor of `load_env` method, I had been changed my config like so (moved working_dir to the top and passed a path to the .env file relative to my app dir)

```ruby
  working_dir $ROOT
  load_env '.env'
```

Eye loads .env file but does not extend ENV hash

**Comment by shlima** [comment]
@kostya, Should I use Eye's DSL `env` method instead of ruby's `ENV` hash to fetch env variables?

**Comment by kostya** [comment]
load_env loading all environments to env, not to ENV. debug your config with `eye explain CONF`
