### ISSUE TITLE
Run passenger

### ISSUE THREAD

**Issue by SergXIIIth** [kostya/eye#130]
Hello Kostya :-)

Could you, please, help me with run passenger via eye. I describe the process, but have problems:

1. `passenger ....................... up  (13:13, 0%, 0Mb, <22439>)` - `0Mb` - I think it indicate problem
2. `eye stop all` - does not stop passenger at all

``` ruby
  process :passenger do
    pid_file "tmp/pids/passenger.pid"

    start_command "#{BUNDLE} exec passenger start --daemonize --socket #{ROOT}/tmp/sockets/opensea-web.sock --pid-file #{ROOT}/tmp/pids/passenger.pid"
    stop_signals [:TERM, 5.seconds, :KILL]
    restart_command "kill -USR2 {PID}"

    restart_grace 15.seconds
  end
```

**Comment by kostya** [comment]
not working with paseanger, but may be it have self daemonizator, which not support signals. may be it should be stopped with custom command.

1) what is 22439, `ps aux | grep 22439`
2) ensure that passenger process pid `ps aux | grep passenger` correctly written in `working_dir/tmp/pids/passenger.pid`

**Comment by kostya** [comment]
this is works for me, i dont know if it have USR2 for grace restart or something, you should read the docs.

```
Eye.application "passenger" do
  env "RAILS_ENV" => 'development'
  working_dir File.expand_path(File.join(File.dirname(__FILE__), %w[ processes ]))

  process("master") do
    pid_file "passenger.pid"
    start_command "bundle exec passenger start -d --pid-file passenger.pid -R thin.ru"
    stop_command "bundle exec passenger stop --pid-file passenger.pid"
    stdall "passenger.log"
    monitor_children
  end

end
```

you cant monitor memory or cpu, because passenger itself is daemonizator, with complex daemonization tree. with eye you only can start stop restart it.

**Comment by SergXIIIth** [comment]
@kostya thank you! Have not try yet, run out of time. Switch to the Puma temporary.
