### ISSUE TITLE
Ability to specify a timeout for eye load

### ISSUE THREAD

**Issue by hackeron** [kostya/eye#131]
My eye config connects to a rails app to fetch information like what cameras are available, unfortunately this takes a short while and eye times out when loading.

It would be great if this timeout could be increased from the command line, e.g.

```
$ eye -t 30 load recorder.eye
```

**Comment by kostya** [comment]
use $ EYE_CLIENT_TIMEOUT=30 eye load ...

**Comment by hackeron** [comment]
Oh, fantastic! - thank you.

Eye is fantastic btw, thank you for making such an awesome gem and fixing all the issues of God and Bluepill.
