### ISSUE TITLE
Q: run eye for self

### ISSUE THREAD

**Issue by niamster** [kostya/eye#132]
I was wondering if it's possible to integrate eye into the existing application to perform self-monitoring out of box(launch client and server in a single process)?
In fact I would like to integrate eye into [DCell](http://github.com/celluloid/dcell) to export stats on memory, CPU and other resources usage.

**Comment by kostya** [comment]
if you need only stats on memory and cpu, and something, just use gem that eye uses `sugar`. I not sure if self monitoring is possible, eye here is hard dependency, easier create actor like this:
```
class Monitor
  include Celluloid
  def initialize
     @sigar = Sigar.new
     every(5) {check_memory}
     every(10) { check_cpu }
  end

  def check_memory
     if @sigar.proc_mem($$) > 1000_000
        Process.kill("TERM", $$)
     end
  end

  ...
end
```
