### ISSUE TITLE
slack notifier doesn't find 'slack-notifier'

### ISSUE THREAD

**Issue by blackjid** [kostya/eye#139]
I'm getting an error when trying to use the slack notification.

```ruby
cannot load such file -- slack-notifier
```

I think the gem `slack-notifier` needs to be a runtime dependency rather a development dependency.
https://github.com/kostya/eye/blob/46dc7a7164b9b51003dbfacd0b77a544e24d28e3/eye.gemspec#L38

**Comment by kostya** [comment]
i think it should not depend on it. you should install 'slack-notifier' by yourself. i think better to create new gem that depend on eye and slack-notifier, like this: https://github.com/tmeinlschmidt/eye-hipchat, it easier to maintain, and remove slack notifier from eye.

**Comment by blackjid** [comment]
I totally agree.

**Comment by tmeinlschmidt** [comment]
hey all, I already added support for slack - https://github.com/tmeinlschmidt/eye-slack :)
