### ISSUE TITLE
Control process resources

### ISSUE THREAD

**Issue by ayashjorden** [kostya/eye#142]
Hi,
I'm experimenting with different process monitors like supervisord and Circus, looking for control on managed process' resources like max-open-files and such.

Reding Eye Wiki and main md, I didn't find such feature.

If there is such feature, can you point me to Eye documentation?

Thanks,
Yarden

**Comment by kostya** [comment]
Right now eye supported only this checks https://github.com/kostya/eye/tree/master/lib/eye/checker. But you can write custom checker, with any feature that supported by `sigar` gem https://support.hyperic.com/display/SIGAR/Home (open files, network usage and such metrics). You can also write your custom checker as eye extension gem.

**Comment by ayashjorden** [comment]
Maybe I'm missing something.
Is Eye is a process manager? can it spawn processes?
If yes, can I set resource limit like nofile ? or the spawned process inherits the user limit configuration?

My intention is not (only) to monitor resource consumption, but to allow resource intensive processes not to be limited by process management system (supervisord limits nofile for 1024, for not reason).

**Comment by kostya** [comment]
Eye mainly is a process manager, it spawn processes, check it for alive, memory, cpu, and something, and restart them if needed. 
File limit should be inherited from eye daemon.

If you want to decrease limit, you can do like this:
```
start_command "sh -c 'ulimit -n 10 && youprocess'"
```
but shell sequences allowed only if youprocess is selfdaemonized (https://github.com/kostya/eye/wiki/About-start_command).

**Comment by ayashjorden** [comment]
Thanks for clarifying this one :)
