### ISSUE TITLE
Eye notification on resolve

### ISSUE THREAD

**Issue by phoolish** [kostya/eye#145]
We receive eye updates when processes crash, but I was wondering if it was possible to then receive an notice when the crash has been resolved.

**Comment by nathwill** [comment]
@phoolish have you looked at using eye-http? we do state and state-transition monitoring via polling of the eye-http port as seen [here](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/eye/check-eye-http-status.rb), which i think would address this?

**Comment by phoolish** [comment]
@nathwill interesting solution.  I don't think it is plausible in the short term to setup API access and add the necessary security layer for our monitoring, but I am interested in that approach as a long term solution.

**Comment by kostya** [comment]
i not think this should be by default, but you can easy do it with custom trigger:
```ruby
class Eye::Trigger::FixCrash < Eye::Trigger::Custom
  param :times, Fixnum, nil, 1
  param_default :to, :up

  def check(_)
    # process states here like this: [..., :starting, :down, :starting, :down, :starting, :up]
    states = process.states_history.states

    # states to compare with
    compare = [:starting, :down] * times + [:starting, :up]
    
    if states[-compare.length..-1] == compare
      process.notify(:info, "yahho, process up")
    end
  end
end

Eye.app :bla do
  trigger :fix_crash

  process :a do
    pid_file '/tmp/1.pid'
    start_command "ruby -e 's = `cat /tmp/bla`; exit(1) unless s =~ /bla/; loop { sleep 1 } '"
    daemonize!
  end
end

```
