### ISSUE TITLE
less strict dependency on celluloid

### ISSUE THREAD

**Issue by pravi** [kostya/eye#146]
can dependency on celluloid be reduced to ~> 0.15 instead of 0.15.0?

**Comment by kostya** [comment]
if you want to use celluloid 0.16, you can use eye 0.7.pre

**Comment by pravi** [comment]
@kostya thanks, that will solve it for now. But is this strict dependency required?

**Comment by kostya** [comment]
For me 0.15.0 used less memory, and as it is system util, usually not needed to add eye to Gemfile and mix dependencies with anything.

**Comment by digitalextremist** [comment]
I'm willing to reduce the memory usage with you, and bring the dependency up to the current version, which is `0.17.0` now. Do you have specific numbers @kostya?

**Comment by kostya** [comment]
i measured long ago, need to repeat

**Comment by kostya** [comment]
tested it again

with ruby 1.9.3 seems no memory difference between celluloid versions (~90Mb on stress test)

with ruby 2.2.2: 
celluloid-0.15: 101Mb
celluloid-0.16: 115Mb
celluloid-0.17: 118Mb

**Comment by digitalextremist** [comment]
Thank you for retesting this. Do you have the benchmark tester somewhere?

I'd like to see how to bring this down.

**Comment by digitalextremist** [comment]
I imagine though that `2.2.2` isn't necessarily `Celluloid` at that level of memory usage, but the RVM itself is bringing on overhead possibly.

Any tests with `rbx` or `jruby` at those two different compatibility levels of `1.9.3` and `2.0+` ?

**Comment by kostya** [comment]
jruby, rbx not supported 

`EYE_V=xxx-yyy bundle exec eye l examples/stress_test.eye`

**Comment by jhass** [comment]
Ping, I'd really like to see celluloid 0.17 compatibility, since sidekiq 2.5 depends on it now.

We use eye in a project where we don't control the target environments, so easy installation by adding it to the Gemfile is essential. Thus the argument to not add it to the Gemfile doesn't work for us, we really need 0.17 compatibility.

**Comment by grimm26** [comment]
I just distribute eye with its own ruby.  Use ruby-install to install whatever ruby you fancy into whatever directory is convenient for you, chruby to it, install eye, package it up, blast it out there.  That way you have no worries about ruby/gem compatabilities with the applications that you are using eye to monitor.

**Comment by digitalextremist** [comment]
I'm willing to patch eye for compatibility, but @kostya has voiced overhead issues. I don't think he's even using 0.16? By 0.18 we hope to bring overhead down in a way that satisfies @kostya. Help on that'd be appreciated.

**Comment by kostya** [comment]
i think i release 0.7 with 0.16 in this week, and 0.8.pre with 0.17. In prod we using celluloid 0.15, which is best for us :)

@grimm26 yes it nice, but too hard to install for users.

**Comment by grimm26** [comment]
maybe I should publish my automation for it...

**Comment by kostya** [comment]
i pushed 0.7 and 0.8.pre

**Comment by jhass** [comment]
Thank you!

**Comment by kostya** [comment]
sad that in production `0.8.pre` leaking for 600Mb per day, `ruby 1.9.3p484`, need to dig more, why it happens.
