### ISSUE TITLE
Disable restart of monitored processes [bounded runtime]

### ISSUE THREAD

**Issue by sereysethy** [kostya/eye#149]
Hello,

I have a problem on how to configure eye so that it will not automatically restart monitors processes. What option should I pass into eye configuration file?

It appears that it reach its bounded runtime.
```
NOTIFY: Bounded runtime: [*360m] send to [:restart]
schedule :restart (reason: bounded runtime)
 => restart  (reason: bounded runtime)
 switch :restarting [:up => :restarting] (reason: bounded runtime)
```

**Comment by kostya** [comment]
check have option :fires, which is by default is :restart 
https://github.com/kostya/eye/blob/master/lib/eye/checker.rb#L26
```
nothing to do:
check :something, :every => 10, ..., :fires => :nothing

notify:
check :something, :every => 10, ..., :fires => :notify

:stop, :start
check :something, :every => 10, ..., :fires => [:stop, :start]
```

**Comment by sereysethy** [comment]
Thanks. 

By the way in my configuration I passed to check following
```
check :runtime, :every => 30.minutes, :below => 360.minutes, :fires => :
nothing
```
so `eye` will check process every 30 minutes until it reaches 360 minutes and then what's next? It will do nothing? and the process still continue to run?

**Comment by sereysethy** [comment]
I got this output from log file of eye.

```
INFO                    check:runtime [*914m] => Fail
ERROR               NOTIFY: Bounded runtime: [*914m] send to [:nothing]
WARN                 :nothing scheduling is unsupported
```

The warning `:nothing scheduling is unsupported`, is it okay? Or because my eye version does not support it?

My eye version `Eye v0.6.4 (c) 2012-2015 @kostya`

**Comment by kostya** [comment]
what you expect here?

**Comment by sereysethy** [comment]
I just want to make sure that output is something intended because I see `:nothing scheduling is unsupported`.

**Comment by kostya** [comment]
this is expected, just message in log

**Comment by sereysethy** [comment]
Thank you very much.
