### ISSUE TITLE
Add checker to check process name.

### ISSUE THREAD

**Issue by cxmcc** [kostya/eye#150]
What I want to do is, send a SIGTERM when my process sidekiq's process name turns to:

```sidekiq 3.4.2 [0 of 4 busy] stopping```

Does it make sense to have a feature to do this? Matching a pattern and do something.

**Comment by kostya** [comment]
What the reason for that? may be it can be solved in another way?

**Comment by cxmcc** [comment]
@kostya nvm, We figured out to do it the right way. Thanks!

**Comment by kostya** [comment]
btw, i added example for such case: https://github.com/kostya/eye/blob/master/examples/custom_check.eye
