### ISSUE TITLE
Clarify configuration options

### ISSUE THREAD

**Issue by fpauser** [kostya/eye#154]
How can eye be configured? As it puts its current pid/sock into `$HOME/.eye/pid|sock` - where to put user-config ($HOME/.eye/config.eye is not working) or system-wide eye-config? (/etc/eye/config.eye would be nice).

**Comment by kostya** [comment]
Our deploy: we create dir /projects/eye/ and symlink projects configs into it, and have the crontab line `@reboot /usr/local/bin/eye load /projects/eye` which is load all configs from that folder on reboot. 

Also, from 0.7 version eye auto loads (with first start):
```
/etc/eye.conf
~/.eyeconfig
```

in this files you can configure some common eye logger options and others...

**Comment by fpauser** [comment]
Thanks for pointing this out - should be documented somewhere.
