### ISSUE TITLE
Help: adding log infos in my-file.eye

### ISSUE THREAD

**Issue by TomFreudenberg** [kostya/eye#156]
Hi,

I want to show additional during my setup of eye inside the my-file.eye but do not get some output too. None from downside will work.

Thanks for a short hint how to use logger inside eye.

Example:

```ruby
# get current working dir from ENV
CWD = ENV['PWD']

# Eye self-configuration section
Eye.config do
  logger File.join(ENV['LOG_PATH'], 'eye.log')
end

#### >>>>>>>
# show CWD
Eye.config.logger.info "THIS DOES NOT WORK"
Eye.config.logger.info CWD

# Eye setup process defines
Eye.application MQWApp.config.app[:title] do

  # set Eye working dir
  working_dir CWD

  #### >>>>>>>
  # show CWD
  info "THIS DOES NOT WORK TOO"
  info CWD
end  
```

**Comment by kostya** [comment]
```ruby
CWD = ENV['CWD']
Eye.info "CWD: #{CWD}"
```

```
CWD=/tmp bundle exec eye l 1.eye -f
```

```
I, [2015-11-16T18:10:39.994760 #3071]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
16.11.2015 18:10:40 INFO  -- [Eye] starting Eye v0.8.pre2 (c) 2012-2015 @kostya <3071>
16.11.2015 18:10:40 INFO  -- [Eye] => command: load /home/kostya/projects/eye/1.eye
16.11.2015 18:10:40 INFO  -- [Eye] => loading: ["/home/kostya/projects/eye/1.eye"]
16.11.2015 18:10:40 INFO  -- [Eye] CWD: /tmp
16.11.2015 18:10:40 INFO  -- [Eye] loading: /home/kostya/projects/eye/1.eye
16.11.2015 18:10:40 INFO  -- [Eye] <= loading: ["/home/kostya/projects/eye/1.eye"]
16.11.2015 18:10:40 INFO  -- [Eye] <= command: load /home/kostya/projects/eye/1.eye (0.020873534s)

```

**Comment by kostya** [comment]
But you should not use ENV variable, because it would not word as you expect: https://github.com/kostya/eye/wiki/Using-ENV-variables-in-config#using-env-variables-in-config

**Comment by TomFreudenberg** [comment]
Thanks for fast response. That was the one I didn't tried ;-)

**Comment by TomFreudenberg** [comment]
Hi @kostya 

That only works when using the parameter "-f" for foregound processing. If you start eye in daemon mode, no own logs are shown?

**Comment by kostya** [comment]
it logged, but not for the first time, load multiple times, and maybe you not see it because it nil

**Comment by TomFreudenberg** [comment]
Ok, something is special on first time start?

also my 

```
require 'relpath/file.rb'
```

does not work at the first time start 

Seems that eye starts the daemon at the first at root "/"

Is there a setting to define the starting directory as well?

**Comment by TomFreudenberg** [comment]
Ok, it is this 

```ruby
  def server_start(configs)
...
    opts = {:out => '/dev/null', :err => '/dev/null', :in => '/dev/null',
            :chdir => '/', :pgroup => true}
```

Why is this necessary on start_server?

**Comment by kostya** [comment]
for the first time logger settled after config eval. for second time logger already settled, so it logged outputs in config.

require is bad, use Eye.load("./file.rb")

**Comment by TomFreudenberg** [comment]
hmm that doesn't fir my needs

I have an app which has some settings loader for a workflow environment

So I want to iterate through my workflow defines to create their processes.

I need to use relative requires because there are files inside my after loading via require. Eye.load() isn't an alternative here.

**Comment by kostya** [comment]
may be you doing something strange?

ok if file.rb loading something relative why not use require_relative in file.rb then?
or, you can hack with load paths, like this:

```ruby
dir = "some/dir"
$:.unshift(dir)
Eye.load("#{dir}/file.rb") 

dir = "some/dir2"
$:.unshift(dir)
Eye.load("#{dir}/file.rb") 
```

**Comment by TomFreudenberg** [comment]
It isn't hacky what I am doing

this is my app folder /home/myapp

<pre>
config
  workflow.yaml

lib
  workflow
    app.rb
    config.rb
    ...
</pr>

app.rb is like

```
require 'lib/workflow/config.rb'
...
```

I normally start my app vi `ruby -I . app/starter.rb`

Whatever ...

If I change on `server.rb` your opts in Line 54-55 from

```ruby
    opts = {:out => '/dev/null', :err => '/dev/null', :in => '/dev/null',
            :chdir => '/', :pgroup => true}
```

```ruby
    opts = {:out => '/dev/null', :err => '/dev/null', :in => '/dev/null',
            :chdir => Dir.pwd, :pgroup => true}
```

everythings works smooth.

Why do want to change it into root instead staying in the directory where eye was called?

**Comment by kostya** [comment]
because eye can be used to load multiple applications from multiple folders. btw `Dir.pwd` may be not bad idea to use with `leye`, but not with `eye`

**Comment by TomFreudenberg** [comment]
Ok, should I try to write my own "eye" loader like leye instead?

**Comment by TomFreudenberg** [comment]
What I want to have is: 

You create a workflow system from our library starting in a sub-folder

Everything you need should stay inside this folder

also the eye process for that workflow system

If someone has a second workflow app in another folder we would create a second eye controlling process, so no system wide eye just a daemon for every app

**Comment by kostya** [comment]
this is concept of `leye`, did you read? https://github.com/kostya/eye/wiki/What-is-loader_eye-and-leye

i think i fix :chdir => Dir.pwd to leye

**Comment by TomFreudenberg** [comment]
I read it once but will try again with your advise now

Btw, in my log on quit I got this warnings

<pre>
16.11.2015 16:19:57 INFO  -- [Eye] <= command: stop_all 600 (1.533095s)
16.11.2015 16:19:57 INFO  -- [Eye] => command: quit
16.11.2015 16:19:57 INFO  -- [Eye] Quit!
16.11.2015 16:19:57 WARN  -- [celluloid] Terminating task: type=:call, meta={:method_name=>:command}, status=:sleeping
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
16.11.2015 16:19:57 WARN  -- [celluloid] Terminating task: type=:call, meta={:method_name=>:run}, status=:iowait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
16.11.2015 16:19:57 WARN  -- [celluloid] Terminating task: type=:call, meta={:method_name=>:handle_connection}, status=:callwait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
</pre>

Is this to ignore or what to do else?

**Comment by kostya** [comment]
it celluloid termination warnings, not a problem

**Comment by TomFreudenberg** [comment]
ok, thanks. 

leye is doing its job as wished ;-)

only part is that chdir to "/"

Where do you like to change that?

**Comment by TomFreudenberg** [comment]
Sry forget my last message ... thanks for the Patch already

Great!!!!!!

**Comment by TomFreudenberg** [comment]
Will you create and upload a new gem release or should I point my app to this git master

**Comment by kostya** [comment]
i think on this week

**Comment by TomFreudenberg** [comment]
Cool, thanks, so I just use the master in the meantime

**Comment by TomFreudenberg** [comment]
@kostya 

I checked your git commit but this would be better if you use

`Dir.pwd`

instead 

`Eye::Local.dir`

because I am not at the point where I am calling leye but where EYE_HOME is pointing to.

So `Dir.pwd` should be the chdir opt.

**Comment by kostya** [comment]
no, Eye::Local.dir is a Eyefile path, so its better, 
because if you in `/you_project/` or in `/you_project/some/dir/`, Eye::Local.dir is always equal `/you_project/`

**Comment by TomFreudenberg** [comment]
hmmm I at `/home/myproject` use the command and option

`leye --eyefile runner.exe load`

but chdir is done to `/home/myproject/.eye`

**Comment by kostya** [comment]
or may be i can fix to use EYE_HOME as starting point of searching Eyefile.

**Comment by kostya** [comment]
ok some little bugs, i'll fix it

**Comment by TomFreudenberg** [comment]
Please mention, when having structure like

/home/myproject
<pre>
config
  runner.eye
lib
  add.rb
app
  project.rb
</pre>

staying at:

/home/myproject

and call

leye --eyefile config/runner.eye load

chdir for process should be at starting point `/home/myproject`

Isn't that `Dir.pwd`?

**Comment by kostya** [comment]
just create Eyefile in /home/myproject with `Eye.load("config/runner.eye")`

cd /home/myproject && leye load, should work, after my fix with /home/myproject/.eye

**Comment by TomFreudenberg** [comment]
Hi @kostya 

sorry, but I have one more:

Why do you have to create that anoying empty `.eye` directory even when I specify

```
EYE_PID
EYE_SOCK
```

and nothing is ever stored in that directory?

file: local.rb / Lines 39-41

```ruby
    def ensure_eye_dir
      FileUtils.mkdir_p(dir)
    end
```

should be better

```ruby
    def ensure_eye_dir
      FileUtils.mkdir_p(dir) unless ENV['EYE_PID'] && ENV['EYE_SOCK']
    end
```

What do you think?

**Comment by kostya** [comment]
i prefer to create .eye, just add it to .gitignore

leye is fixed in master,
you can play with example:
```
bundle exec leye --eyehome examples/leye_example l
bundle exec leye --eyehome examples/leye_example i
bundle exec leye --eyefile examples/leye_example/Eyefile i
bundle exec leye --eyehome examples/leye_example q -s
```

**Comment by TomFreudenberg** [comment]
Hi, I have rewritten leye to my needs inside our project.

Now I can fix load the process table from our workflow

we call it:

`ruby -I . lib/eye/mqw-eye.rb load`

"our" leye is named `mqw-eye.rb`

```ruby
# Create processes from mqw workflow

# get settings from MQW
require "lib/mqw/mqw-app"

# define locations
EYE_LOG_PATH = File.join(MQWApp.app_logpath, "eye")
EYE_RUN_PATH = File.join(MQWApp.app_runpath, "eye")

# set location for pid_file and sock_file if not given
ENV['EYE_PID']  = File.join(EYE_RUN_PATH, 'eye.pid')  unless ENV['EYE_PID']
ENV['EYE_SOCK'] = File.join(EYE_RUN_PATH, 'eye.sock') unless ENV['EYE_SOCK']
ENV['EYE_FILE'] = File.join(File.expand_path(MQWApp.app_filepath), "mqw-conf.rb")

# start eye process
require 'eye'
Eye::Local.local_runner = true
Eye::Cli.start
```

our config script:

`lib/eye/mqw-conf.rb`

```ruby
# Initialize eye processing engine from workflow

# check and save current working dir
raise "Could not locate current directory via $PWD env-var! Please check." unless ENV['PWD']
CWD = ENV['PWD']

# make sure that this process is located where it was started
# see issue and discussion at: https://github.com/kostya/eye/issues/156#issuecomment-157084798
Dir.chdir(CWD)

# append local local path to include requires etc.
$LOAD_PATH.unshift(".")

# use MQW
require "lib/mqw/mqw-app"

# force to reload settings
MQWApp.load_config

# use log-rotate extension
require 'eye'
require 'eye-rotate'

# define locations
EYE_LOG_PATH = File.join(MQWApp.app_logpath, "eye")
EYE_RUN_PATH = File.join(MQWApp.app_runpath, "eye")

# Eye self-configuration section
Eye.config do
  # create logger for mqw-eye process
  logger File.join(EYE_LOG_PATH, 'eye.log')
  # setup log file rotation
  log_rotate :every => MQWApp.settings.eye[:log_rotate][:duration],
             :count => MQWApp.settings.eye[:log_rotate][:count],
             :gzip  => MQWApp.settings.eye[:log_rotate][:compress]
end

# Eye setup process defines
Eye.application MQWApp.config.app[:title] do

  # set Eye working dir
  working_dir CWD
  
  trigger :flapping, times: 10, within: 1.minute
  check :memory, below: 60.megabytes, every: 30.seconds, times: 5

  # Loop through all defined workers/queues
  MQWApp.workflow.workers.keys.each do |identifier|
    # get options from worker definition
    worker_options = MQWApp.create_worker_options(identifier)
    # loop through process elements of worker and services
    ['', 'retry_', 'abort_'].each do |section|
      # build symbols to inspect based on section
      process_symbol = (section + 'process').to_sym
      queue_symbol = (section + 'queue_name').to_sym
      # test for process and positive number of processes
      if worker_options[process_symbol] && worker_options[process_symbol][:processes] && (worker_options[process_symbol][:processes] > 0)
        # create that Eye process description
        worker_options[process_symbol][:processes].times do |iCnt|
          # set process identifier
          process_name = "#{worker_options[queue_symbol]}_#{iCnt + 1}"
          # describe process
          process process_name do
            # define settings
            pid_file File.join(EYE_RUN_PATH, process_name + ".pid")
            stdall   File.join(EYE_LOG_PATH, worker_options[queue_symbol] + ".log")

            # set default process params
            keep_alive          worker_options[process_symbol][:keep_alive]         || MQWApp.settings.eye[:process][:keep_alive]
            check_alive_period  worker_options[process_symbol][:check_alive_period] || MQWApp.settings.eye[:process][:check_alive_period]
            daemonize           worker_options[process_symbol][:daemonize]          || MQWApp.settings.eye[:process][:daemonize]
            auto_start          worker_options[process_symbol][:auto_start]         || MQWApp.settings.eye[:process][:auto_start]

            # set default process timeouts and signals
            start_timeout       worker_options[process_symbol][:start_timeout]      || MQWApp.settings.eye[:process][:start_timeout]
            start_grace         worker_options[process_symbol][:start_grace]        || MQWApp.settings.eye[:process][:start_grace]
            stop_timeout        worker_options[process_symbol][:stop_timeout]       || MQWApp.settings.eye[:process][:stop_timeout]
            stop_grace          worker_options[process_symbol][:stop_grace]         || MQWApp.settings.eye[:process][:stop_grace]
            restart_timeout     worker_options[process_symbol][:restart_timeout]    || MQWApp.settings.eye[:process][:restart_timeout]
            restart_grace       worker_options[process_symbol][:restart_grace]      || MQWApp.settings.eye[:process][:restart_grace]
            stop_signals        worker_options[process_symbol][:stop_signals]       || MQWApp.settings.eye[:process][:stop_signals]

            # build command line
            command = MQWApp.settings.command[worker_options[process_symbol][:command]]
            script = worker_options[process_symbol][:script]
            params = worker_options[process_symbol][:params]

            # check mandatory settings for process
            raise NameError, "Missing settings for command type #{worker_options[process_symbol][:command]}!" unless command
            raise NameError, "Missing script identifier for #{worker_options[queue_symbol]}!" unless script
            raise NameError, "Could not locate script: #{script}!" unless File.exist?(script)

            # execute command
            start_command (command + " " + script + " " + params).strip

            # check { :memory, "below" => 300.megabytes, "times" => 3 }
            check (:memory, below: 300.megabytes, times: 3)
          end
        end
      end
    end
  end

end
```

**Comment by TomFreudenberg** [comment]
The config is done by YAML.

It would really be great if you could decide NOT to create .eye in any way. Still no sense when setting your already allowed ENV_VARs

**Comment by TomFreudenberg** [comment]
The last I am struggling with is how "externalize" things like `checks` and `triggers` into our YAML config.

Do you have any idea how to save 

```ruby
check :memory, below: 300.megabytes, times: 3
```

in an additional ruby script file or YAML and load on demand during config?

**Comment by kostya** [comment]
if you create your own leye, then you also can just redefine function
```ruby
module Eye::Local
  class << self
    def ensure_eye_dir
      FileUtils.mkdir_p(dir) unless ENV['EYE_PID'] && ENV['EYE_SOCK']
    end
  end
end
```

about checks you can see how eye-patch save yaml configs: https://github.com/tablexi/eye-patch

**Comment by TomFreudenberg** [comment]
;-) sometimes life can be so easy. Thanks

**Comment by TomFreudenberg** [comment]
Btw. - Thanks for "eye" - I really like it! 

The documentation is a bit behind what this tool can do. So it takes its time to find out about functioniality.

**Comment by TomFreudenberg** [comment]
Its a pity but the redefine is not working.

I guess "autoload" in eye.rb will reload and override the patch sometime.

---

I will have a look at eye-patch module

**Comment by TomFreudenberg** [comment]
Thanks for hinting to eye-patch. I have adapted that as shown:

```ruby
            # short names
            __wo = worker_options[process_symbol]

            # append checks
            if __wo[:checks]
              # loop the defined checks
              __wo[:checks].each do |check|
                # rewrite from yaml to symbols
                type_sym = check['type'].to_sym
                options_sym = {}
                check['options'].each { |opt| options_sym[opt[0].to_sym] = opt[1] }
                # append check to process
                checks(type_sym, options_sym)
              end
            end 
```

that is a part from YAML

```yaml
      :process:
        :command:               'ruby'
        :script:                'test/test-eye-simple-service.rb'
        :params:                ''
        :processes:             1
        :checks:
          - { type: cpu, options: { times: [ 3, 5 ], every: 10, below: 30 } }
        :triggers:
          - { type: flapping, options: { times: 10, within: 60, retry_in: 60, retry_times: 5 } }
```
