### ISSUE TITLE
Error: using eye on cygwin - sigar does not compile

### ISSUE THREAD

**Issue by TomFreudenberg** [kostya/eye#157]
Hi, we are using our workflow engine also on top of Windows 2012 with installed cygwin environment and ruby 2.2.3.

No that I have embed your eye component, we could not get it run there, because sigar does not build. To many errors and I haven't the time to fix it yet.

Is it possible to run eye without sigar? I am not sure if you use sigar only for optional checker like cpu and memory.

Thanks for a short hint
Tom

**Comment by kostya** [comment]
god and bluepill used `ps -p ..`, eye used too ago. which was so bad because not compatible, and can give so little system information. sigar is super good. i am not going to remove it.

sigar used for checks, and also in `eye i`

if you want to remove sigar you should rewrite class Eye::SystemResources in some other way.

**Comment by TomFreudenberg** [comment]
Hi, I do not want you to remove the sigar gem, just asking if we could get are system updated with last changes. Otherwise I have to drop out all from tonight :-( only for that cygwin stuff.

I just try to make a quick'n dirty drop of Sigar for the moment.

**Comment by kostya** [comment]
try to create issue in sigar, but seems sigar right now is not maintained :( and i don't know solution better than sigar. you can also see commit where sigar appear in eye. da07f9d6015b5c08eb01a8f2e32b10d9941b4476

**Comment by kostya** [comment]
if you not using checks, disable check_identity by option `check_identity false`, not using `eye i`, then seems you not hit the sigar.

**Comment by TomFreudenberg** [comment]
I tried just the very quick n dirty option at:

https://github.com/4commerce-technologies-AG/eye/commits/mqw-eye

but that doesn't work. I get that kind of errors

<pre>
--------------------------------------------------------------
      2 [main] ruby 3644 C:\Opm\cygwin\bin\ruby.exe: *** fatal error in forked process - can't commit memory for stack 0x6FFFF0FA6D0(0xFFFFF90100115930), Win32 error 87
   1817 [main] ruby 3644 cygwin_exception::open_stackdumpfile: Dumping stack trace to ruby.exe.stackdump
      1 [unknown (0x122C)] ruby 4016 fork: child -1 - forked process 3644 died unexpectedly, retry 0, exit code 0x100, errno 11
1033324 [main] ruby 4936 C:\Opm\cygwin\bin\ruby.exe: *** fatal error in forked process - can't commit memory for stack 0x6FFFF0FA6D0(0xFFFFF90100115930), Win32 error 87
1035058 [main] ruby 4936 cygwin_exception::open_stackdumpfile: Dumping stack trace to ruby.exe.stackdump
1108974 [unknown (0x122C)] ruby 4016 fork: child -1 - forked process 4936 died unexpectedly, retry 0, exit code 0x100, errno 11
2143005 [main] ruby 4692 C:\Opm\cygwin\bin\ruby.exe: *** fatal error in forked process - can't commit memory for stack 0x6FFFF0FA6D0(0xFFFFF90100115930), Win32 error 87
2145067 [main] ruby 4692 cygwin_exception::open_stackdumpfile: Dumping stack trace to ruby.exe.stackdump
2180177 [unknown (0x122C)] ruby 4016 fork: child -1 - forked process 4692 died unexpectedly, retry 0, exit code 0x100, errno 11
Interrupted, exit now...
</pre>

Any idea ? I am a bit despaired.

**Comment by kostya** [comment]
no idea, not sure if eye possible to run on windows

**Comment by kostya** [comment]
you add many raises, i think it bad because celluloid always restart actor.
just remove sigar dependency and if "not using checks, disable check_identity by option  check_identity false , not using  eye i  (or stub Eye::SystemResources.resources(pid) to return {}), not using monitor_children, then seems you not hit the sigar."

**Comment by TomFreudenberg** [comment]
Hi @kostya 

Thanks for help but I can't make it. I haven't yet enough experience in your library to do all the changes in the right way as mentioned.

So for now I guess I have to give up here and check for an alternative

(I added ps_aux to system.rb https://github.com/4commerce-technologies-AG/eye/commit/547f3723f25087beb04c3310b66c4c0a26400c04 but that isn't the point gets hit currently)

**Comment by TomFreudenberg** [comment]
It is really frustrating ... bluepill and god are both installed without problems on cygwin. I really like your eye gem but maybe you have to add some better compatible mode if sigar is not available. Also depending on a yet (not well) maintained component isn't a good one.

**Comment by kostya** [comment]
i pushed branch `no_sigar` https://github.com/kostya/eye/commit/196ea5651207ddc79f6bcf1277943a76edd42614, you can try it.

**Comment by kostya** [comment]
sigar is super stable for us, so we continue to use it.

**Comment by TomFreudenberg** [comment]
It seems, that there are more conflict in using eye and its gem dependencies on cygwin / windows.

I have setup a clean 64bit cygwin on a new machine, get everything compiled but when starting, same memory error:

<pre>
I, [2015-11-17T16:38:34.037726 #4292]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
17.11.2015 16:38:35 INFO  -- [Eye] starting Eye v0.8.pre2 (c) 2012-2015 @kostya <4292>
17.11.2015 16:38:35 INFO  -- [Eye] => command: load /var/mqw/topline/lib/eye/mqw-conf.rb
17.11.2015 16:38:35 INFO  -- [Eye] => loading: ["/var/mqw/topline/lib/eye/mqw-conf.rb"]
      0 [main] ruby 3108 C:\Opm\cygwin\bin\ruby.exe: *** fatal error in forked process - can't commit memory for stack 0x6FFFF0FA6D0(0xFFFFF90100115930), Win32 error 87
    762 [main] ruby 3108 cygwin_exception::open_stackdumpfile: Dumping stack trace to ruby.exe.stackdump
      0 [unknown (0x13D4)] ruby 4292 fork: child -1 - forked process 3108 died unexpectedly, retry 0, exit code 0x100, errno 11
</pre>

I try once more to install 32bit cygwin and see whats happen then

**Comment by TomFreudenberg** [comment]
No, also on cygwin 32bit I got the same errors when forking new processes

**Comment by TomFreudenberg** [comment]
@kostya - in case that eye is not working on windows what alternative would you suggest?

bluepill or god - I have no experiences in any or do you have another suggestion for my requirements?

Thanks for a short feedback
Tom

---

Thanks for help in any case

**Comment by kostya** [comment]
no idea, not using windows many years.

**Comment by TomFreudenberg** [comment]
And if you had to decide between bluepill and god?

**Comment by kostya** [comment]
i dont like it both, not used them for 3 years. god seems better than bluepill.
