### ISSUE TITLE
eye stuck up and resque not processing

### ISSUE THREAD

**Issue by nguyenchiencong** [kostya/eye#161]
From time to time, my resque tasks stop processing and eye info gives: eye timed out without responding...

Any advice? I think it's related to the latest updates as it has never happened before.

Thx

**Comment by nguyenchiencong** [comment]
More info: ruby 2.3.0

**Comment by kostya** [comment]
timed out usually happens when eye moved to swap, may be you have so little memory on server. What the last ok eye version? Also with 1.9.3 eye used less memory.

**Comment by nguyenchiencong** [comment]
Hi, indeed we use a lot of memory but that should not happen like that. The last ok version was eye (0.6.4) with ruby 2.2.2.

**Comment by kostya** [comment]
Yes it should not. May be you leave too few free memory on the server (how many?). How many memory eye daemon used? is eye in swap? (cat /proc/{PID}/status | grep Vm). From 0.6.4 eye updated celluloid dependency (0.15 -> 0.17) which is used more memory.

**Comment by kostya** [comment]
Also what in eye log when the problem happens.

**Comment by kostya** [comment]
at least you can try eye v '0.8.celluloid15', which is like 0.8 but used old celluloid (so it should be equally to 0.6.4).

**Comment by nguyenchiencong** [comment]
Thx a lot for the quick reply. I will try that and get back to you.

**Comment by nguyenchiencong** [comment]
I just check this in normal state. I will check it again when the server is under heavy memory load

```
VmPeak:	 3421708 kB
VmSize:	 3381256 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   74848 kB
VmRSS:	   74416 kB
VmData:	 3314108 kB
VmStk:	    8192 kB
VmExe:	    2976 kB
VmLib:	    6460 kB
VmPTE:	    1708 kB
VmPMD:	      28 kB
VmSwap:	       0 kB
```

**Comment by nguyenchiencong** [comment]
eye info still hangs with those info:
```
VmPeak:	 3421708 kB
VmSize:	 3374600 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   74912 kB
VmRSS:	   74520 kB
VmData:	 3307452 kB
VmStk:	    8192 kB
VmExe:	    2976 kB
VmLib:	    6460 kB
VmPTE:	    1692 kB
VmPMD:	      28 kB
VmSwap:	       0 kB
```

**Comment by kostya** [comment]
Looks like this is not memory problem. Maybe you have so big Load Average or Disk Usage on the server, so eye client responding slow. try `EYE_CLIENT_TIMEOUT=100 eye i`. if this not working too, you should find in eye log where the problem.

**Comment by nguyenchiencong** [comment]
Last time I checked EYE_CLIENT_TIMEOUT=100 eye i , it still hangs.
Just to let you know that '0.8.celluloid15' seems to work and the problem is no more happening.

**Comment by kostya** [comment]
if 0.8.celluloid15 works, nice, please help to find problem in 0.8. 

add to config:

```ruby
Eye.config do
  logger '/tmp/eye.log'
  logger_level Logger::DEBUG
end
```

and find in log where the problem was, may be some exception, or something.

**Comment by nguyenchiencong** [comment]
Sure I'll do that tomorrow when the service is no more critical

**Comment by nguyenchiencong** [comment]
Sorry for the late reply. I don't think I can risk my production environment this time. Do you have any other way to replicate this problem?

**Comment by kostya** [comment]
so 0.8.celluloid15 works fine for long, and 0.8 have problems after some hours (on ruby 2.3.0)?
diff between this versions is only https://github.com/kostya/eye/compare/v0.8.celluloid15?expand=1
(updated celluloid version)

may be you can reproduce it on some stagging environment?
