### ISSUE TITLE
Eye crashes on starting sidekiq

### ISSUE THREAD

**Issue by nisa** [kostya/eye#164]
```
executing: `bundle exec sidekiq -e production` with start_timeout: 30.0s, start_grace: 2.5s, env: ' '( in /opt/project_dir/current')
`{:error=>#<Errno::ENOENT: No such file or directory - open>}`
switch :crashed [:starting => :down] (reason: crashed)

```
Any help appreciated.

**Comment by kostya** [comment]
show eye config

**Comment by nisa** [comment]
``def load_env
  File.open('/opt/grasshopper/.env', 'rb').each_line do |line|
    result = line.split('=')
    env result[0] => result[1].chop if result.length > 1
  end

  # unicorn requires to be `ruby` in path (for soft restart)
  env "PATH" => "/usr/local/bin/ruby:#{ENV['PATH']}"
end

Eye.config do
  logger "/tmp/eye.log"
end

Eye.application "community-cloud" do

  load_env
  group "community-cloud-web" do
    chain :grace => 5.seconds

    process 'community-cloud-web-1' do
      working_dir "/opt/grasshopper/community_cloud/current"
      pid_file "/opt/grasshopper/community_cloud/tmp/pids/unicorn.pid"
      start_command 'bundle exec unicorn -E production -Dc ./config/unicorn.rb'

      stop_signals [:QUIT, 10.seconds, :TERM, 10.seconds, :KILL]
      # stop_signals [:TERM, 10.seconds]
      restart_command "kill -USR2 {PID}"
      stdall "/var/log/community-cloud/community-cloud-web-1.log"


      # check :cpu, :every => 30, :below => 80, :times => 3
      # check :memory, :every => 30, :below => 150.megabytes, :times => [3,5]

      start_timeout 30.seconds
      # restart_timeout 30.seconds
      restart_grace 30.seconds
      stop_timeout 30.seconds

      monitor_children do
        stop_command "kill -QUIT {PID}"

        # check :cpu, :every => 30, :below => 80, :times => 3
        # check :memory, :every => 30, :below => 150.megabytes, :times => [3,5]
      end
    end
  end

  group "community-cloud-worker" do
    chain :grace => 5.seconds

    process 'community-cloud-worker-1' do
      working_dir "/opt/grasshopper/community_cloud/current"
      pid_file "/opt/grasshopper/community_cloud/tmp/pids/sidekiq.pid"
      daemonize true
      start_command "bundle exec sidekiq -e production"
      #stop_signals [:usr1, 30.seconds, :term, 5.seconds, :kill]
      stop_signals [:QUIT, 5.seconds, :TERM, 5.seconds, :KILL]

      stdall "/var/log/message-service/community-cloud-worker-1.log"

      start_timeout 30.seconds
      restart_timeout 30.seconds
      stop_timeout 30.seconds

      monitor_children do
        stop_command "kill -QUIT {PID}"
      end
    end
  end
end

**Comment by kostya** [comment]
ensure that dirs `/opt/grasshopper/community_cloud/current` and `/var/log/message-service/` exists. Also ensure that eye have permissions to create file `/var/log/message-service/community-cloud-worker-1.log`

btw, there is already method `load_env "/opt/grasshopper/.env"`
