### ISSUE TITLE
Single eye instance across all system

### ISSUE THREAD

**Issue by mikeys** [kostya/eye#168]
I was wondering if it's possible to configure `eye`'s single user.
Currently every time I run `eye w` (for example), it's being ran in the context of the running user and produces the error (`socket(/home/<user>/.eye/sock) not found, did you run ``eye load`` ?`), as opposed to a system wide context that I would expect.

Currently, in order to see the right results, I need to switch to the deploying user `sudo su xxx` and only then `eye w` produces the expected results. Any idea?

**Comment by kostya** [comment]
create alias?

```
eye="sudo -u eye -H eye"
```

then `eye w`, should be `sudo -u eye -H eye w`

**Comment by kostya** [comment]
another way is change eye home dir:

```
EYE_HOME=/tmp/ eye l conf.eye
EYE_HOME=/tmp/ eye w
```

this would work from any user, but not from root (for root need to fix this: https://github.com/kostya/eye/issues/166)

**Comment by mikeys** [comment]
@kostya Thanks for the quick response, appreciate that :)
