### ISSUE TITLE
cannot match targets from different applications

### ISSUE THREAD

**Issue by pschrammel** [kostya/eye#169]
Is there any reason not to allow matches from different applications?

**Comment by kostya** [comment]
because matching is wide, you can accidentally restart something that you don't want to restart. when you want to restart 2 processes from different apps is a quite strange use case.

**Comment by pschrammel** [comment]
well in my case a god process is watching one app which consists of different processes (delayed_job, messagbus_daemon, other_daemons). So I have different applications. The apps are in different (restart) groups (some apps have to be restarted on each deploy others only in very special cases). I could implement a config flag that allows/disallows this security feature. Would you accept a pull request for such a feature?

**Comment by kostya** [comment]
you should use masks:
```
eye restart app1*some,app2*some
```

**Comment by pschrammel** [comment]
my mask is: eye restart *:deploy:* (this is a application agnostic script, that doesn't know anything about the specific applications); it just knows if this is a setup / deploy / .... situation and uses according masks *:deploy:* *:setup:* (I want to use this mechanism for all my apps on opsworks).

**Comment by kostya** [comment]
now i see a reason, i think i add this: when mask starts with `*`, we not check this condition.

**Comment by pschrammel** [comment]
wow would be cool! I'm currently switching from god to eye and this is the last shop stopper
