### ISSUE TITLE
Kill wrong process when timeout?

### ISSUE THREAD

**Issue by emn178** [kostya/eye#170]
Hi,

I had a thin server and pid is *6706*. I stopped services by eye. It ran the stop command but timeout. I saw that eye sent the KILL signal to *9595*. Finally, my service failed to stop. It seems that eye send signal to wrong process.
```
10.04.2016 16:42:05 INFO  -- [faye] executing: `bundle exec thin -P faye.pid stop` with stop_timeout: 10.0s and stop_grace: 0.5s
10.04.2016 16:42:15 WARN  -- [Eye::System] [faye] sending :KILL signal to <9595> due to timeout (10s)
10.04.2016 16:42:15 ERROR -- [faye] stop_command failed with #<Timeout::Error: execution expired>; try tuning the stop_timeout value
10.04.2016 16:42:15 INFO  -- [faye] sleeping for :stop_grace 0.5
10.04.2016 16:42:15 WARN  -- [faye] process <6706> was not stopped; try checking your command/signals or tuning the stop_timeout/stop_grace values
10.04.2016 16:42:15 INFO  -- [faye] switch :unmonitoring [:stopping => :unmonitored] (reason: not stopped (soft command))
10.04.2016 16:42:15 INFO  -- [faye] switch :unmonitoring [:unmonitored => :unmonitored] (reason: stop by user)
```

**Comment by kostya** [comment]
kill signal was sent to stop_command(not to faye), which is timeouted, try to increase stop_timeout interval which is 10s by default.
Show you stop_command, also measure how many seconds, it executed if you run it by hands.

**Comment by emn178** [comment]
Stop command
`bundle exec thin -P faye.pid stop`
Is it better to replace by `stop_signals [:QUIT, 2.seconds, :TERM, 1.seconds, :KILL]` in example?

**Comment by kostya** [comment]
if you daemonize process with eye(daemonize true), surely better to use signals. if process self-daemonized, you also can use signals, but not in all cases (for example unicorn, passanger require special signals, to correctly stop all children).
