### ISSUE TITLE
Configuration can not reload

### ISSUE THREAD

**Issue by emn178** [kostya/eye#172]
Hi,

I run command `eye load conf.rb` after daemon started. In document, it says this will update configurations but it doesn't. I have to `eye quit` and restart to reload configuration. Is it normal?

Thanks.

**Comment by kostya** [comment]
not normal, you can check what config is loaded by `eye x -c`
and also check what in eye log:
```
Eye.config do
  logger "/tmp/eye.log"
end
```

**Comment by emn178** [comment]
Hi,

After testing, I found the problem seems that config from `require`.
I have a main config, it looks like this:
```Ruby
$apps = ['path/to/app', 'path/to/app2']
# ...
$apps.each {|app| require File.join(app, 'eye.rb') }
```
In this case, it can not reload by main config.

**Comment by kostya** [comment]
thats why you should use Eye.load

**Comment by emn178** [comment]
Thanks, it works. I didn't see that.
