### ISSUE TITLE
invalid process status 'stopping'

### ISSUE THREAD

**Issue by ktimothy** [kostya/eye#176]
I have a process, that can take up to 1 hour to quit after I call `eye restart`. If I run multiple `eye restart` commands before process actually restarts, eye shows process status as 'stopping', but does not send any signals.

I had to manually kill process several times before eye changed process status to 'up'. I guess there is some kind of a queue, where eye stores restart commands?

UPD: eye also does not perform any checks, if process is in 'stopping' state. Is this behavior intentional?

**Comment by kostya** [comment]
yes there is a queue of commands, and other commands wait until stop_command end. stopping by a hour little strange case. and this is common case when you should stop process first, before start another one, because it commonly uses the same port for example. so we just set stop_commands like `stop_commands :QUIT, 10.seconds, :TERM, 20.seconds, :KILL`, to ensure kill it after 30 seconds.

**Comment by kostya** [comment]
actually you can stop process by a hour, but it should be self-daemonized.

**Comment by kostya** [comment]
similar issue https://github.com/kostya/eye/issues/52

**Comment by ktimothy** [comment]
But the problem is that eye does not run next queued stop_command, when process is running again.

I am talking about sidekiq process. I have tasks, that can take a lot of time to finish, and I cannot allow any of them to fail beacuse of killed sidekiq process. So, I have to wait before sidekiq finishes them.

**Comment by kostya** [comment]
if you send 2 restart commands, as i remember second not scheduled, while first executed

**Comment by kostya** [comment]
such tasks for 1 hour for task manager system, its pain in any case. may be split to many small tasks. or use crontab for this

**Comment by ktimothy** [comment]
> its pain in any case.
No pain at all - I just send TERM signal, and sidekiq quits after finishing active task.

> if you send 2 restart commands, as i remember second not scheduled, while first executed
But why eye didn't change process state to 'up'? Well, maybe I should create a minimal config, that reproduces the issue.

**Comment by kostya** [comment]
yes show config, and how reproduce problem.
