### ISSUE TITLE
Eye starts work processes with different timestamps

### ISSUE THREAD

**Issue by SOLDIERz** [kostya/eye#182]
We are using eye for multiple of our projects but we are always facing an Issue with one system. We restart our app but from time to time the timestamp differ from the timestamp on all other nodes. Is there any reason why this is happening?

**Comment by kostya** [comment]
may be this? https://github.com/kostya/eye/issues/35

**Comment by SOLDIERz** [comment]
@kostya so it's and sigar Issue and there is no way around that? I'm right here?

**Comment by kostya** [comment]
yes, but sigar quite useful, and there is no equal replace for this gem. is there any problem with wrong timestamps?

**Comment by kostya** [comment]
this should be fixed in 0.10.0
