### ISSUE TITLE
Signal to eye to tell it to load?

### ISSUE THREAD

**Issue by grimm26** [kostya/eye#184]
I tried sending eye a HUP but that just causes it to shut down.

**Comment by kostya** [comment]
why do you mean? eye to reload all configs? there is no such function. you should just call `eye load config` to reload/update it.

**Comment by kostya** [comment]
if you have many configs, you can put symlinks of it in one dir, /etc/eye/, and reload all of it. `eye load /etc/eye/`

**Comment by grimm26** [comment]
I would like to be able to send it a signal as part of a systemd service config to reload the config.

**Comment by kostya** [comment]
this is not possible right now, because eye not storing file paths, but i think should not be hard to implement

**Comment by grimm26** [comment]
I found that I can use an ExecReload setting in a systemd unit file, too, instead of just sending a signal.  I should be fine for now, then.
