### ISSUE TITLE
Eye.load inside of Eye.application block

### ISSUE THREAD

**Issue by grimm26** [kostya/eye#188]
I use Chef to manage my systems and I'm trying to lay out a config directory structure for Eye configs to handle configs being set for one or more applications under Eye.
The main config file would be /etc/eye/main.eye and I have it like:
```
::Dir.glob('/etc/eye/conf.d/*') do |file|
  next unless ::File.directory?(file)
  app_name = ::File.basename(file)
  Eye.application app_name do
    Eye.load(::File.join(file, '*.eye'))
  end
end
```
So they layout would be /etc/eye/conf.d/`application`/`process`.eye and there could be multiple process files and multiple applications.

The problem is that I can't Eye.load inside of an Eye.application block.  I also tried moving the Eye.application block into the process files, but only the one process config is loaded then.  The other option seems to make the process config files contain methods that I can call inside of the Eye.application block after loading the process configs.

Is it possible to add to an application outside of the original Eye.application block?
Is there a way to load process definitions inside of an Eye.application block?

**Comment by kostya** [comment]
you can load files, which contain for example:
1.eye
```ruby
def bla
  process :bla do
     ...
  end
end
```

2.eye
```ruby
def foo
  process :foo do
     ...
  end
end
```


main.eye
```
Eye.load("./processes/*.eye")
Eye.app :some do
  bla
  foo
end
```

**Comment by kostya** [comment]
also there is such way to include app: https://github.com/kostya/eye/blob/master/spec/dsl/sub_procs_spec.rb

**Comment by kostya** [comment]
https://github.com/kostya/eye/blob/145b6ca66bc602d1950a8064676df58a97c0e4fa/spec/fixtures/dsl/include_test.eye
