### ISSUE TITLE
Can I pass arguments to config file in load command?

### ISSUE THREAD

**Issue by joshweir** [kostya/eye#194]
Hi Eyes

I'd like to pass arguments to the config file in the load command theoretically like this:

`eye load my.eye 10`

    #my.eye
    my_param = ARGV[0] #<- my_param = 10

Is there any way to do this? 

Thanks
Josh

**Comment by kostya** [comment]
No, but use some external config:
```
config = YAML.load_file("/some/config.yml")
my_param = config['param']
```
