### ISSUE TITLE
Maybe remove sigar dependency?

### ISSUE THREAD

**Issue by xanview** [kostya/eye#196]
Seems sigar has not been maintained in years, I'm not able to compile it in Alpine linux and it does not work inside of a Docker container, something I'm hoping to switch to.

Is there any other alternative to remove this dependency?

**Comment by kostya** [comment]
https://github.com/kostya/eye/issues/192

**Comment by xanview** [comment]
Ah, that's amazing, thank you! - Will test and report any issues
