### ISSUE TITLE
Idempotence of `eye load`

### ISSUE THREAD

**Issue by msabdeljalil** [kostya/eye#200]
I'm trying to load an eye config with multiple services, but I might not always want all those services to start when I load the config. Additionally, this behavior only occurs on first load - subsequent calls to `eye load` do not start the services the way the first call does.

To overcome this problem, one currently has to create separate eye applications for what would otherwise be just multiple processes within a single application.

Might It might make sense to separate this functionality?

**Comment by kostya** [comment]
try:
```ruby
Eye.app :bla do
  auto_start false
end
```

**Comment by msabdeljalil** [comment]
Yep that works! Ty!
