### ISSUE TITLE
Why root directory is hard coded?

### ISSUE THREAD

**Issue by chrisortman** [kostya/eye#206]
I'm running into a problem with this behavior 

https://github.com/kostya/eye/blob/145b6ca66bc602d1950a8064676df58a97c0e4fa/lib/eye/local.rb#L9

I run `leye` as a non-privileged user with no login shell. 
When I do this I specify that `EYE_HOME` should point to some directory.
This makes it so that as a root user I can not run any eye commands because the `sock` is never found as it always looks in the `/var/run` directory

**Comment by grimm26** [comment]
You can/should also set EYE_SOCK and EYE_PID

**Comment by kostya** [comment]
should work in 0.9.4

**Comment by chrisortman** [comment]
Thanks!
