### ISSUE TITLE
kostya-sigar does not compile with glibc-2.27 on Arch linux

### ISSUE THREAD

**Issue by wollistik** [kostya/eye#213]
Hi,

I liked to open an issue in kostya-sigar, but issues are disabled there? So I make this one here.
The latest version of glibc (2.27 at this time) is compiled without --enable-obsolete-rpc flag and therefore many of rpc/*.h files are not included any more in the package.
sigar_util.c depends on them and won't compile. I don't have the C-skills to fix it myself :-(

As alternative you could switch from sigar to sys-proctable, which seems to have all needed features for eye and is under active development. Then I would be able to do the work for you and create a pull request.

**Comment by wollistik** [comment]
That would be nice! +1

**Comment by kostya** [comment]
can you check kostya-sigar 2.0.2?

**Comment by wollistik** [comment]
Tested and works like a charm!
