### ISSUE TITLE
Add another process to existing application

### ISSUE THREAD

**Issue by jbmyid** [kostya/eye#215]
I am trying to create separate eye files per process and trying to load. but last loaded process replaces existing one.

Is there any way to add process in already defined application?

**Comment by kostya** [comment]
no, application should be described fully. in your case, you should create 2 applications.

**Comment by jbmyid** [comment]
how about grouping the processes. 
eg: resque job i want to group but also want to be separate files as it should be flexible to run/add it for particular instance.

Actually we were using god and that was very useful.

**Comment by kostya** [comment]
you can separate you process descriptions to multiple files, but application should be defined fully as one block. you can add or remove processes from this app, and just recall `load`. examples: https://github.com/kostya/eye/blob/master/examples/thin-farm.eye, and https://github.com/kostya/eye/blob/master/examples/process_thin.rb

**Comment by kostya** [comment]
also example https://github.com/kostya/eye/wiki/About-stop_on_delete-=-true

**Comment by jbmyid** [comment]
Thanks, i had to go with multi application approach. It would be really great if processes can be added after application loading.

**Comment by kostya** [comment]
just add process to application config and load config again, process would be added, you just need to have application config somewhere (in your application)
