### ISSUE TITLE
How to send restart signal if my check is true?

### ISSUE THREAD

**Issue by abigoroth** [kostya/eye#218]
hi.. I have check as below
```
class MyCheck < Eye::Checker::Custom

  def get_value
    tmp = eval(`cat /home/system/dnsvault/ws_ping.txt`)
    last_ping = tmp["message"]
    puts ((Time.now - Time.at(last_ping)) > 60)
    (Time.now - Time.at(last_ping)) > 60
  end

  def good?(value)
    value !~ /haha/
  end

end
```

and in my config like this 
```
check :my_check, every: 10.seconds
```
how can I send restart signal if my check is true?

**Comment by kostya** [comment]
all checks by default send :restart, when `good?` method returns false, you can change it by:
```
check :my_check, every: 10.seconds, :fires => :stop
```

you `good?` method seems bad, it should check value from get_value function.

**Comment by abigoroth** [comment]
thanks kostya <3 .
tons of love from Malaysia.
