### ISSUE TITLE
How to make sure log files are rotated or don't grow 

### ISSUE THREAD

**Issue by rept** [kostya/eye#226]
I've changed this:

logger '/production/current/log/eye.log'

into

logger '/production/current/log/eye.log', 7, 5.megabytes

But this doesn't affect the daemonized processes right?

I have a process:

```
process :sneakers do
    daemonize true
    pid_file "/production/current/tmp/pids/sneakers.pid"
    stdall "/production/current/log/sneakers.log"

    start_command "bundle exec rake sneakers:run"
    stop_signals [:TERM, 5.seconds, :KILL]
    restart_command 'kill -9 {PID}'

    restart_grace 10.seconds
  end
end

```

How can I make sure the sneakers.log never grows beyond XX MB ?

**Comment by kostya** [comment]
use eye-rotate gem
