### ISSUE TITLE
Weird Eye::SystemResources.start_time behaviour

### ISSUE THREAD

**Issue by ilyakorol** [kostya/eye#235]
I receive in logs a very frustrating row:
```
2020.05.12 10:10:46 WARN  -- [sidekiq:sidekiq_0] compare_identity: fail, pid_file: '12 May 10:09', process: '12 May 10:15' (sidekiq 6.0.1 platform [0 of 5 busy])
```
As far as I understand, `Eye::SystemResources.start_time` returns time in future (log time is 10:10, but start time is 10:15). 
How is that even possible?

**Comment by kostya** [comment]
may be similar https://github.com/kostya/eye/issues/35

**Comment by ilyakorol** [comment]
fixed after system reboot, it looks like exactly the same issue.
