### ISSUE TITLE
How to load the processes without starting them?

### ISSUE THREAD

**Issue by matheusvetor** [kostya/eye#242]
Hi, i do have a collection of rails apps running together inside one docker container and orchertrated by eye. Each rails app has a bunch of rake commands that i need to keep running. So I have one god file to tell to eye all processes it need to run. My issue is: I have too much rake commands and i dont want them to start automatically with eye, only be available to start manually with `eye start <rake task name>`

Like example below, i only need to start automatically the rails apps

```
app1
  rails ............... starting
  rake_task ....... starting
  rake_task ........ starting
  rake_task ... starting
app2
  rails .................. starting
app3
  rails ............... starting
  rake_task ....... starting
  rake_task ........ starting
  rake_task ... starting
app4
  rails ............... starting
  rake_task ....... starting
  rake_task ........ starting
  rake_task ... starting
app5
  rails ............... starting
  rake_task ....... starting
  rake_task ........ starting
  rake_task ... starting
app6
  rails ............... starting
  rake_task ....... starting
  rake_task ........ starting
  rake_task ... starting
```

**Comment by kostya** [comment]
you can enable option chain: example: https://github.com/kostya/eye/blob/master/examples/thin-farm.eye#L23C45-L23C45
or set `auto_start false`

**Comment by matheusvetor** [comment]
Thanks.
