### ISSUE TITLE
Managing eye with upstart

### ISSUE THREAD

**Issue by cgunther** [kostya/eye#34]
I've got eye set up for managing my Rails and Sidekiq processes, however I wanted to manage eye via Upstart to start eye on boot and monitor eye incase it dies unexpectedly.

I've tried with all three variations on the `expect` stanza:
- no `expect` stanza (0 forks)
- `expect fork` (1 fork)
- `expect daemon` (2 forks)

And each time, Upstart ends up tracking a different PID than what eye is running on.

Following Upstarts documentation for getting the fork count (http://upstart.ubuntu.com/cookbook/#how-to-establish-fork-count), the strace log returns a value of 17, which seems excessively high.

Here's the Upstart config I'm using for reference:

```
description 'Eye'

start on runlevel [2]
stop on runlevel [016]

expect daemon

exec su -l -c 'eye load /home/deploy/sample.eye' deploy

respawn
```

Process forking is a bit new to me in Ruby, so I'm hoping someone else can shed some light on this for me.

Once it's solved, I'll gladly work up a wiki page to help document this for future users.

Thanks in advance!

**Comment by stufently** [comment]
I try use your upstart script , its work fine for start, but stop and restart dont work.
I use upstart  1.12.1-0ubuntu4.2 in ubuntu 14.04

**Comment by rmldsky** [comment]
Yup, struggling with the same issue as @stufently, will post if I manage to find a solution. Or did you (@stufently) managed to sort this out?

**Comment by kostya** [comment]
there is in wiki https://github.com/kostya/eye/wiki/Manage-with-upstart, may be it works?

**Comment by stufently** [comment]
Maybe  my upstart script help you
/etc/init/eye.conf                                                                                                      341/341               100%
description 'Eye'

start on (local-filesystems and runlevel [2345])
stop on runlevel [016]

setuid deploy
setgid deploy

respawn
expect fork
console log
env EYE_HOME=/home/deploy

script
    export HOME=/home/deploy
    exec eye load /home/deploy/sites/asgapi/shared/asgapi.eye
end script


post-stop script
  eye quit --stop_all
end script

**Comment by rmldsky** [comment]
@kostya saw this one, but also had no luck with it.

@stufently thanks, I actually had a similar one and as long as staring worked, stop did not for me. 

In both those cases `stop` was the thing not working for me, as PID for service spawned by Upstart differ from the actual PID of running eye daemon. Which is expected here I guess ;).

For now I ended up with different solution which I grabbed from some "unicorn in Upstart" tutorial:
```
description 'Eye'

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]
kill timeout 60

setuid ubuntu
setgid ubuntu

# log stdout and stderr to /var/log/upstart/eye
console log

script
  # Eye runs from $HOME, upstart with setuid wont set $HOME
  export HOME=/home/ubuntu
  eye load /var/www/app/current/config/eye/app.eye 
  # After above point we/Upstart lose control of eye daemon here due to PID mismatching
  while true; do
    # Sleep forever. The backgrounding (&) + wait is so that "trap" can
    # interrupt at any time. A plain "sleep infinity" wouldn't allow this.
    sleep infinity & BLOCKING_PID=$!
    # When interrupted by a trap, wait dies with exit code 128; ignore this, keep going.
    wait "$BLOCKING_PID" || true
  done
end script

post-stop script
  export HOME=/home/ubuntu #Here needed as well. See coment above.
  eye quit -s # Stop all eye services, and quit eye
end script 
```

Not the prettiest solution, but hopefully temporary won't become permanent ;)

**Comment by kostya** [comment]
you can run eye without daemonization,
there is internal loader_eye process

```
loader_eye --help
Usage: loader_eye [options]
    -h, --help                       Display this screen
    -c, --config CONFIG              load with config
    -s, --socket SOCKET              start listen on socket
    -l, --logger LOGGER              custom logger
    -d, --dir DIR                    Dir for local runner
    -a, --stop_all                   Stop all on exit
    -g, --debug                      debug info to logger
```

example:
```
bundle exec loader_eye -c config_dir/ -l /tmp/eye.log -a
```

**Comment by rmldsky** [comment]
And the `Duh!` goes to me ;), will check this out, thanks! 

Though the more I relay on a setup like `Upstart`-> `eye`-> `app stuff`, the less I find it convenient. I'd rather drop either `Upstart` or `eye` here. I need to give it more thoughts and testing.

**Comment by kostya** [comment]
i don't know why you need upstart at all, we using only crontab to run eye after server reboot, and eye works without restart for years
